# Change these first
owner: DimensionDev
repo: Firefly_service_status

sites:
  - name: Firefly API (prod)
    url: https://api.firefly.land/
  - name: Firefly API (dev)
    url: https://api-dev.firefly.land/
  - name: RSS3 Notes
    url: $RSS3_NOTES_URL
    method: POST
    headers:
      - "accept: application/json"
      - "content-type: application/json"
    body: $RSS3_NOTES_PARAM
  - name: RSS3 Profiles
    url: $RSS3_PROFILES_URL
    method: POST
    headers:
      - "accept: application/json"
      - "content-type: application/json"
    body: $RSS3_PROFILES_PARAM
  - name: BlockTracker `get_whale_list`
    url: $BT_URL
  - name: BlockTracker `get_whale_feed`
    url: $BT_WHALE_FEED
  - name: BlockTracker `get_profile_by_id`
    url: $BT_PROFILE
  - name: NFTScan `own/all`
    url: $NFTSCAN_OWN_ALL
    headers:
      - "X-API-KEY: $NFTSCAN_X_API_KEY"
  - name: NFTScan `filters`
    url: $NFTSCAN_FILTERS
    headers:
      - "X-API-KEY: $NFTSCAN_X_API_KEY"
    method: POST
    body: NFTSCAN_FILTERS_PARAM
  - name: NFTScan `assets`
    url: $NFTSCAN_ASSETS
    headers:
      - "X-API-KEY: $NFTSCAN_X_API_KEY"
  - name: Test API down
    url: https://www.testdown.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Firefly_service_status
  logoUrl: https://raw.githubusercontent.com/DimensionDev/Firefly_service_status/master/assets/firefly-logo.png
  name: Firefly service status
  introTitle: "Firefly Service Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /Firefly_service_status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
